# Generated by Django 5.0.7 on 2024-07-10 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discounted_proce',
            new_name='discounted_price',
        ),
    ]
